CREATE TABLE IF NOT EXISTS teachers (
    id SERIAL PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    subject VARCHAR(100),
    email VARCHAR(150) UNIQUE NOT NULL,
    class VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
